# Generated by Django 5.1.3 on 2025-03-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListePatient',
        ),
    ]
