# Generated by Django 5.1.7 on 2025-04-26 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0002_rendezvous_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='heure_debut',
            new_name='duree',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='description',
            new_name='motif',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='heure_fin',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='Datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en-attente', 'En-attente'), ('reserve', 'Réservé'), ('repote', 'Reporte'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='reserve', max_length=10),
        ),
    ]
