# Generated by Django 5.1.7 on 2025-05-01 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0003_rename_heure_debut_rendezvous_duree_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé le rendez-vous', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdvs_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='modifie_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a modifié le rendez-vous (annulé, confirmé, reporté...)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdvs_modifies', to=settings.AUTH_USER_MODEL),
        ),
    ]
