# Generated by Django 5.1.7 on 2025-05-01 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0007_alter_rendezvous_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='cree_par',
        ),
    ]
