# Generated by Django 5.1.7 on 2025-05-01 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0008_remove_rendezvous_cree_par'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé le rendez-vous', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdvs_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
