# Generated by Django 5.1.3 on 2025-05-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_maladiecronique_sub_nom'),
        ('rendez_vous', '0009_rendezvous_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='consultation.consultation'),
        ),
    ]
