# Generated by Django 5.1.3 on 2025-05-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0010_ordonnance_consultation'),
        ('rendez_vous', '0010_rendezvous_gender'),
    ]

    operations = [
    ]
