# Generated by Django 5.2.1 on 2025-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0011_merge_20250525_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='duree',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
