# Generated by Django 5.2.1 on 2025-05-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendez_vous', '0012_alter_rendezvous_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='gender',
        ),
    ]
