from django.urls import path
from .views import (
    CreateRendezVousView,
    CreateRendezVousParPatientView,
    OrdonnanceDetailByConsultationView,
    OrdonnanceDetailView,
    PatientOrdonnanceListView,
    OrdonnanceCreateView,
    OrdonnanceListView,
    CreateDemandeRendezVousView,
    PlageHoraireListView,
    UpdatePlageHoraireStatusView,
    SupprimerPlageEtAnnulerRDV,
    CreatePlageHoraireView,
    confirmer_demande,
    annuler_demande,
    annuler_demande_patient,
    reporter_demande,
    demandes_rendez_vous,
    demandes_annulation,
)

urlpatterns = [
    path('createrenderVousMedAss/<int:patient_id>/', CreateRendezVousView.as_view(), name='create-rendezvous-medass'),
    path('create/<int:patient_id>/', CreateRendezVousView.as_view(), name='create-rendezvous'),
    path('createPatient/', CreateRendezVousParPatientView.as_view(), name='create-rendezvous-patient'),
    path('ordonnance/consultation/<int:consultation_id>/', OrdonnanceDetailByConsultationView.as_view(), name='ordonnance-detail-by-consultation'),
    path('ordonnance/<int:id>/', OrdonnanceDetailView.as_view(), name='ordonnance-detail'),
    path('ordonnances/patient/', PatientOrdonnanceListView.as_view(), name='patient-ordonnance-list'),
    path('ordonnance/create/<int:pk>/', OrdonnanceCreateView.as_view(), name='ordonnance-create'),
    path('ordonnances/', OrdonnanceListView.as_view(), name='ordonnance-list'),
    path('demande/create/', CreateDemandeRendezVousView.as_view(), name='create-demande-rendezvous'),
    path('plages-horaires/', PlageHoraireListView.as_view(), name='plage-horaire-list'),
    path('plage-horaire/update/', UpdatePlageHoraireStatusView.as_view(), name='update-plage-horaire'),
    path('plage-horaire/supprimer/', SupprimerPlageEtAnnulerRDV.as_view(), name='supprimer-plage-et-annuler-rdv'),
    path('plage-horaire/create/', CreatePlageHoraireView.as_view(), name='create-plage-horaire'),
    path('demandes-rendez-vous/', demandes_rendez_vous, name='demandes-rendez-vous'),
    path('demandes-annulation/', demandes_annulation, name='demandes-annulation'),
    path('confirmer-demande/<int:demande_id>/', confirmer_demande, name='confirmer-demande'),
    path('annuler-demande/<int:demande_id>/', annuler_demande, name='annuler-demande'),
    path('annuler-demande-patient/<int:demande_id>/', annuler_demande_patient, name='annuler-demande-patient'),
    path('reporter-demande/<int:demande_id>/', reporter_demande, name='reporter-demande'),
]