# Generated by Django 5.1.3 on 2025-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_pics/image.jpg', upload_to='profile_pics'),
        ),
    ]
