# Generated by Django 5.2.1 on 2025-05-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Homme'), ('Female', 'Femme')], max_length=10, null=True, verbose_name='Sexe'),
        ),
    ]
