# Generated by Django 5.1.7 on 2025-04-16 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DossierMedicale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='dossier_medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DossierMedicale.dossiermedical'),
        ),
        migrations.AddField(
            model_name='dossiermedicalenseignant',
            name='dossier_documents',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='DossierMedicale.document'),
        ),
        migrations.AddField(
            model_name='dossiermedicaletudiant',
            name='dossier_documents',
            field=models.ManyToManyField(blank=True, related_name='etudiants', to='DossierMedicale.document'),
        ),
        migrations.AddField(
            model_name='dossiermedicalfonctionnaire',
            name='dossier_documents',
            field=models.ManyToManyField(blank=True, related_name='fonctionnaires', to='DossierMedicale.document'),
        ),
    ]
