# Generated by Django 5.1.3 on 2025-04-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depistage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_auditive', models.CharField(choices=[('normal', 'Normal'), ('perte_auditive', 'Perte auditive'), ('surdite', 'Surdité partielle/complète')], max_length=50)),
                ('utilisation_audiometre', models.BooleanField()),
                ('test_reponse_son', models.CharField(choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=20)),
                ('remarque_audition', models.TextField(blank=True, null=True)),
                ('vision_lointaine', models.CharField(choices=[('normale', 'Normale'), ('anormale', 'Anormale')], max_length=20)),
                ('vision_proche', models.CharField(choices=[('normale', 'Normale'), ('anormale', 'Anormale')], max_length=20)),
                ('besoin_lunettes', models.BooleanField()),
                ('test_snellen_effectue', models.BooleanField()),
                ('remarque_vision', models.TextField(blank=True, null=True)),
                ('pression_oculaire', models.CharField(choices=[('normale', 'Normale'), ('anormale', 'Anormale')], max_length=20)),
                ('examen_fond_oeil', models.CharField(choices=[('normal', 'Normal'), ('anormal', 'Anormal')], max_length=20)),
                ('tests_ophtalmo_suppl', models.CharField(choices=[('necessaire', 'Nécessaire'), ('non_necessaire', 'Non nécessaire')], max_length=20)),
                ('maladies_oculaires_detectees', models.TextField(blank=True, null=True)),
                ('examen_nez', models.CharField(choices=[('sain', 'Sain'), ('inflammation', 'Inflammation'), ('obstruction_chronique', 'Obstruction chronique')], max_length=40)),
                ('examen_oreille', models.CharField(choices=[('saine', 'Saine'), ('inflammation', 'Inflammation'), ('autre_probleme', 'Autre problème')], max_length=40)),
                ('examen_larynx', models.CharField(choices=[('normal', 'Normal'), ('inflammation', 'Inflammation'), ('probleme_voix', 'Problèmes de voix')], max_length=40)),
                ('remarque_orl', models.TextField(blank=True, null=True)),
                ('doosier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DossierMedicale.dossiermedical')),
            ],
        ),
    ]
