# Generated by Django 5.1.3 on 2025-05-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0002_depistage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depistage',
            name='doosier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DossierMedicale.dossiermedical'),
        ),
    ]
