# Generated by Django 4.2.7 on 2025-04-30 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0002_depistage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='categorie_imc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='imc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='depistage',
            name='doosier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='DossierMedicale.dossiermedical'),
        ),
    ]
