# Generated by Django 5.1.7 on 2025-03-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0002_remove_dossiermedical_patient_dossiermedical_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossiermedicaletudian',
            old_name='Fielier',
            new_name='Filiere',
        ),
    ]
