# Generated by Django 5.1.7 on 2025-05-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0003_dossiermedical_categorie_imc_dossiermedical_imc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='categorie_imc',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='imc',
        ),
        migrations.AlterField(
            model_name='depistage',
            name='doosier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DossierMedicale.dossiermedical'),
        ),
    ]
