# Generated by Django 5.1.7 on 2025-03-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0003_rename_fielier_dossiermedicaletudian_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
