# Generated by Django 5.1.3 on 2025-05-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0003_alter_depistage_doosier'),
        ('DossierMedicale', '0004_remove_dossiermedical_categorie_imc_and_more'),
    ]

    operations = [
    ]
