# Generated by Django 5.1.3 on 2025-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0004_dossiermedical_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedicalenseignant',
            name='grade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dossiermedicalfonctionnaire',
            name='grade',
            field=models.CharField(max_length=20),
        ),
    ]
