# Generated by Django 4.2.7 on 2025-04-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0004_dossiermedical_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='dossier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='medical_dossiers/'),
        ),
    ]
