# Generated by Django 4.2.7 on 2025-04-03 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0006_document_remove_dossiermedical_dossier_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dossier_medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DossierMedicale.dossiermedical'),
        ),
    ]
