# Generated by Django 4.2.7 on 2025-04-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0007_document_dossier_medical'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedicaletudian',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='etudiants', to='DossierMedicale.document'),
        ),
    ]
