# Generated by Django 4.2.7 on 2025-04-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0008_dossiermedicaletudian_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DossierMedicalEtudian',
            new_name='DossierMedicalEtudiant',
        ),
        migrations.RenameField(
            model_name='dossiermedicaletudiant',
            old_name='documents',
            new_name='dossier_documents',
        ),
    ]
