# Generated by Django 4.2.7 on 2025-04-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0005_alter_dossiermedicalenseignant_grade_and_more'),
        ('DossierMedicale', '0009_rename_dossiermedicaletudian_dossiermedicaletudiant_and_more'),
    ]

    operations = [
    ]
