# Generated by Django 4.2.7 on 2025-04-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0010_merge_20250407_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedicalenseignant',
            name='dossier_documents',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='DossierMedicale.document'),
        ),
        migrations.AddField(
            model_name='dossiermedicalfonctionnaire',
            name='dossier_documents',
            field=models.ManyToManyField(blank=True, related_name='fonctionnaires', to='DossierMedicale.document'),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='admission_etablissement',
            field=models.CharField(default='Oui', max_length=50),
        ),
    ]
