# Generated by Django 4.2.7 on 2025-04-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierMedicale', '0011_dossiermedicalenseignant_dossier_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
