# Generated by Django 5.1.7 on 2025-04-26 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rendez_vous', '0003_rename_heure_debut_rendezvous_duree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField(blank=True, null=True, verbose_name='Poids')),
                ('taille', models.FloatField(blank=True, null=True, verbose_name='Taille')),
                ('tensionArterielle', models.FloatField(blank=True, null=True, verbose_name='Tension artérielle')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Température')),
                ('frequenceCardiaque', models.FloatField(blank=True, null=True, verbose_name='Fréquence cardiaque')),
                ('status', models.CharField(choices=[('prise_en_charge', 'Prise en charge'), ('oriente', 'Orienté')], default='prise_en_charge', max_length=20, verbose_name='Statut')),
                ('rendezvous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rendez_vous.rendezvous', verbose_name='consultation')),
            ],
        ),
        migrations.CreateModel(
            name='MaladieContagieuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la maladie')),
                ('status', models.CharField(choices=[('prise_en_charge', 'Prise en charge'), ('oriente', 'Orienté')], default='prise_en_charge', max_length=20, verbose_name='Statut')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation', verbose_name='Consultation')),
            ],
        ),
        migrations.CreateModel(
            name='MaladieCronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la maladie')),
                ('status', models.CharField(choices=[('prise_en_charge', 'Prise en charge'), ('oriente', 'Orienté')], default='prise_en_charge', max_length=20, verbose_name='Statut')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation', verbose_name='Consultation')),
            ],
        ),
    ]
