# Generated by Django 5.2.1 on 2025-05-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_remove_maladiecontagieuse_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Homme'), ('Female', 'Femme')], max_length=10, null=True, verbose_name='Sexe'),
        ),
    ]
