# Generated by Django 5.1.3 on 2025-05-23 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_remove_maladiecontagieuse_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consultation',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10),
        ),
    ]
