# Generated by Django 5.1.3 on 2025-05-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultation_date_consultation_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladiecronique',
            name='sub_nom',
            field=models.CharField(default='Diabète', max_length=100),
        ),
    ]
