# Generated by Django 5.2.1 on 2025-05-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_consultation_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='gender',
        ),
    ]
