# Generated by Django 5.1.3 on 2025-05-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_maladiecronique_sub_nom'),
        ('consultation', '0004_remove_consultation_gender'),
    ]

    operations = [
    ]
