# Generated by Django 5.1.7 on 2025-04-16 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rendez_vous', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEMANDE_RDV_RECUE', 'Demande de rendez-vous reçue'), ('RDV_CONFIRMEE', 'Rendez-vous confirmé'), ('RDV_ANNULE', 'Rendez-vous annulé'), ('RDV_RAPPORTE', 'Rendez-vous raporté a une autre date'), ('RDV_PLANNIFIE', 'Nouveau rendez-vous plannifié'), ('RDV_TERMINE', 'Rendez-vous terminé'), ('RDV_EN_ATTENTE', 'Rendez-vous en attente'), ('RAPPEL_RDV', 'Rappel de rendez-vous')], default='DEMANDE_RDV_RECUE', help_text='Type de notification', max_length=50)),
                ('message', models.TextField(help_text='Contenu de la notification')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lien_action', models.URLField(blank=True, help_text="Lien vers l'action ou la ressource associée", null=True)),
                ('rendez_vous', models.ForeignKey(blank=True, help_text='Rendez-vous concerné par la notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='rendez_vous.rendezvous')),
                ('user', models.ForeignKey(help_text='Utilisateur qui reçoit la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
