# Generated by Django 5.1.7 on 2025-05-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
    ]
